// app/layout.tsx
import ClientProtected from "@/components/ProtectedRoutes/ClientProtected";
import { BudgetProvider } from "@/context/BudgetContext";
import { AuthProvider } from "@/context/AuthContext";
import Header from "@/components/Header/Header";
import { ReactNode } from "react";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Budget Workflow",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang="en">
			<head>
				<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Mali:wght@400;700&display=swap" />
			</head>
			<body style={{ fontFamily: "Mali, sans-serif" }}>
				<AuthProvider>
					<Header />
					<BudgetProvider>
						<ClientProtected>{children}</ClientProtected>
					</BudgetProvider>
				</AuthProvider>
			</body>
		</html>
	);
}
